//
//  Pillarbox.swift
//  Core
//
//  Created by Andreas Pfurtscheller on 07.04.21.
//

import Foundation
import AVFoundation

/// This struct provides a scope for global structures and enums that need to be accessible publicly.
public struct Pillarbox {

    /// This enum is used for all errors that are generated by this library.
    /// Any external errors are wrapped within more descriptive ones.
    public enum Error: Swift.Error {

    }
}

extension Pillarbox.Error: LocalizedError {

    public var errorDescription: String? {
        return nil
    }
}
