name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: ncipollo/release-action@v1
      with:
        name: Pillarbox ${{ env.RELEASE_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}

